#!/usr/bin/env bash
set -euo pipefail

# Motivation experiment: external-memory query breakdown for PGM and RMI.
# Runs O_DIRECT and a 128MB LRU page cache by default, reads the first QUERY_LIMIT queries from each table,
# repeats each run, averages repeated results, then plots.
# Intended to run over the books_200M join workloads generated by:
#   DATASET=books_200M_uint64_unique bash exp/run_books200m_join_workloads.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

BINARY="${BINARY:-./build/motivation_query_breakdown}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
DATASETS_DIRECTORY="${DATASETS_DIRECTORY:-/mnt/data/Dataset/public/SOSD}"
DATASET="${DATASET:-osm_cellids_200M_uint64_unique}"
QUERY_TAG="${QUERY_TAG:-1M}"
TABLE_LIST="${TABLE_LIST:-1 2 3 4 5 6}"
BASELINES="${BASELINES:-RMI-DIRECT PGM-DIRECT}"
OUT_CSV="${OUT_CSV:-build/log/motivation/osm_cellids_200M_query_breakdown.csv}"
RAW_CSV="${RAW_CSV:-${OUT_CSV%.csv}_raw.csv}"
IO_TABLE_CSV="${IO_TABLE_CSV:-build/log/motivation/osm_cellids_200M_io_size_table.csv}"
TMP_DIR="${TMP_DIR:-build/log/motivation/tmp}"
FIGURE_DIR="${FIGURE_DIR:-data/outputs/figures/motivation}"
PLOT_OUTPUT="${PLOT_OUTPUT:-$FIGURE_DIR/osm_cellids_200M_query_breakdown_stacked}"
PLOT_LABELS="${PLOT_LABELS:-w1 w2 w3 w4 w5 w6}"
RMI_DATA_DIR="${RMI_DATA_DIR:-src/rmi/rmi_data}"
RMI_GENERATED_DIR="${RMI_GENERATED_DIR:-src/rmi/rmi_eval/generated}"
RMI_MODELS="${RMI_MODELS:-linear_spline,linear}"
RMI_MODEL_TAG="${RMI_MODEL_TAG:-linear_spline_linear}"
RMI_PREFIX="${RMI_PREFIX:-}"
RMI_GENERATE="${RMI_GENERATE:-1}"
RMI_GENERATOR_SCRIPT="${RMI_GENERATOR_SCRIPT:-exp/generate_rmi_headers.sh}"
RMI_TRAIN_SOURCE_PATH="${RMI_TRAIN_SOURCE_PATH:-$DATASETS_DIRECTORY/$DATASET}"
RMI_TRAIN_DATA_PATH="${RMI_TRAIN_DATA_PATH:-src/rmi/dataset/${DATASET}_fixed}"
RMI_COLLECT_RECORDS="${RMI_COLLECT_RECORDS:-0}"
RMI_COLLECT_DATA_PATH="${RMI_COLLECT_DATA_PATH:-$DATASETS_DIRECTORY/$DATASET}"
RMI_COLLECT_DATA_HEADER="${RMI_COLLECT_DATA_HEADER:-no}"
RMI_COLLECT_QUERY_PATH="${RMI_COLLECT_QUERY_PATH:-$DATASETS_DIRECTORY/$DATASET.${QUERY_TAG}table1.bin}"
RMI_LEAF_ERROR_DIR="${RMI_LEAF_ERROR_DIR:-data/outputs/motivation/rmi_leaf_errors}"

NUM_KEYS="${NUM_KEYS:-200000000}"
HEADER_MODE="${HEADER_MODE:-auto}"
EPS_LIST="${EPS_LIST:-24}"
BF_LIST="${BF_LIST:-262144}"
STRATEGY="${STRATEGY:-all_in_once}"
QUERY_LIMIT="${QUERY_LIMIT:-10000}"
CACHE_POLICY="${CACHE_POLICY:-LRU}"
CACHE_BYTES="${CACHE_BYTES:-134217728}"
REPEATS="${REPEATS:-5}"
BUILD="${BUILD:-1}"
CONFIGURE="${CONFIGURE:-1}"
PLOT="${PLOT:-1}"
PLOT_FORMATS="${PLOT_FORMATS:-pdf}"
BUILD_JOBS="${BUILD_JOBS:-$(nproc 2>/dev/null || printf '4')}"

if [ -z "$RMI_PREFIX" ]; then
  case "$DATASET" in
    books*) RMI_PREFIX="books_rmi" ;;
    fb*) RMI_PREFIX="fb_rmi" ;;
    *) RMI_PREFIX="${DATASET%%_*}_rmi" ;;
  esac
fi

DEFAULT_RMI_BF_LIST="64 128 256 512 1024 2048 4096 8192 16384 32768 65536 131072 262144 524288 1048576 2097152"

csv_list() {
  printf '%s\n' "$1" | tr ' ' ',' | tr -s ','
}

expand_branch_factor_list() {
  local spec="$1"
  local normalized
  normalized="$(printf '%s\n' "$spec" | tr ',' ' ')"
  for token in $normalized; do
    case "$(printf '%s' "$token" | tr '[:upper:]' '[:lower:]')" in
      all)
        printf '%s\n' "$DEFAULT_RMI_BF_LIST"
        return 0
        ;;
    esac
  done
  printf '%s\n' "$normalized"
}

EPS_CSV="$(csv_list "$EPS_LIST")"
BF_CSV="$(csv_list "$BF_LIST")"
STRATEGY_CSV="$(csv_list "$STRATEGY")"

if [ "$REPEATS" -lt 1 ]; then
  echo "[error] REPEATS must be >= 1" >&2
  exit 2
fi

if [ "$BUILD" = "1" ]; then
  if [ "$CONFIGURE" = "1" ]; then
    echo "[configure] build"
    cmake -S . -B build
  fi
  echo "[build] motivation_query_breakdown"
  cmake --build build --target motivation_query_breakdown -j "$BUILD_JOBS"
fi

if [ ! -x "$BINARY" ]; then
  echo "[error] missing binary: $BINARY" >&2
  echo "        Build it first, e.g. cmake --build build --target motivation_query_breakdown" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT_CSV")" "$(dirname "$RAW_CSV")" "$(dirname "$IO_TABLE_CSV")" "$TMP_DIR" "$RMI_LEAF_ERROR_DIR" "$RMI_GENERATED_DIR"

common_args=(
  --data "$DATASETS_DIRECTORY/$DATASET"
  --keys "$NUM_KEYS"
  --header "$HEADER_MODE"
  --rmi-data-dir "$RMI_DATA_DIR"
  --rmi-generated-dir "$RMI_GENERATED_DIR"
  --rmi-prefix "$RMI_PREFIX"
  --rmi-model-tag "$RMI_MODEL_TAG"
  --strategies "$STRATEGY_CSV"
  --cache-policy "$CACHE_POLICY"
  --cache-bytes "$CACHE_BYTES"
)

if [ "$QUERY_LIMIT" -gt 0 ]; then
  common_args+=(--query-limit "$QUERY_LIMIT")
fi

append_repeat_csv() {
  local run_csv="$1"
  local raw_csv="$2"
  local repeat_id="$3"
  "$PYTHON_BIN" - "$run_csv" "$raw_csv" "$repeat_id" <<'PY_APPEND'
import csv
import sys
from pathlib import Path

run_csv = Path(sys.argv[1])
raw_csv = Path(sys.argv[2])
repeat_id = sys.argv[3]

with run_csv.open(newline="") as src:
    reader = csv.DictReader(src)
    if reader.fieldnames is None:
        raise SystemExit(f"empty run csv: {run_csv}")
    fieldnames = ["repeat"] + reader.fieldnames
    write_header = not raw_csv.exists() or raw_csv.stat().st_size == 0
    with raw_csv.open("a", newline="") as dst:
        writer = csv.DictWriter(dst, fieldnames=fieldnames)
        if write_header:
            writer.writeheader()
        for row in reader:
            writer.writerow({"repeat": repeat_id, **row})
PY_APPEND
}

average_repeat_csv() {
  local raw_csv="$1"
  local out_csv="$2"
  "$PYTHON_BIN" - "$raw_csv" "$out_csv" <<'PY_AVERAGE'
import sys
from pathlib import Path

import pandas as pd

raw_csv = Path(sys.argv[1])
out_csv = Path(sys.argv[2])
df = pd.read_csv(raw_csv)
if df.empty:
    raise SystemExit(f"empty raw csv: {raw_csv}")

original_cols = [col for col in df.columns if col != "repeat"]
group_cols = [
    col for col in [
        "label",
        "baseline",
        "io_mode",
        "index_type",
        "model",
        "epsilon",
        "branch_factor",
        "index_bytes",
        "policy",
        "cache_bytes",
        "strategy",
    ] if col in df.columns
]

for col in df.columns:
    if col in group_cols or col in {"repeat", "checksum"}:
        continue
    converted = pd.to_numeric(df[col], errors="coerce")
    if converted.notna().any():
        df[col] = converted

agg = {}
for col in original_cols:
    if col in group_cols:
        continue
    if col == "checksum":
        agg[col] = "first"
    elif pd.api.types.is_numeric_dtype(df[col]):
        agg[col] = "mean"
    else:
        agg[col] = "first"

out = df.groupby(group_cols, as_index=False, sort=False).agg(agg)
repeat_counts = (
    df.groupby(group_cols, as_index=False, sort=False)["repeat"]
    .nunique()
    .rename(columns={"repeat": "repeats"})
)
out = out.merge(repeat_counts, on=group_cols, how="left", sort=False)
out = out[[col for col in original_cols if col in out.columns] + ["repeats"]]
out_csv.parent.mkdir(parents=True, exist_ok=True)
out.to_csv(out_csv, index=False, float_format="%.6f")
PY_AVERAGE
}

write_io_size_table() {
  local summary_csv="$1"
  local table_csv="$2"
  "$PYTHON_BIN" - "$summary_csv" "$table_csv" <<'PY_IO_TABLE'
import re
import sys
from pathlib import Path

import pandas as pd

summary_csv = Path(sys.argv[1])
table_csv = Path(sys.argv[2])
df = pd.read_csv(summary_csv)
required = [
    "label",
    "index_type",
    "io_size_mean_bytes",
    "io_size_std_bytes",
    "io_size_p50_bytes",
    "io_size_p95_bytes",
]
missing = [col for col in required if col not in df.columns]
if missing:
    raise SystemExit(f"missing IO-size columns in {summary_csv}: {missing}")

def workload_name(label):
    text = str(label)
    match = re.fullmatch(r"table(\d+)", text)
    return f"w{match.group(1)}" if match else text

def label_order(label):
    match = re.fullmatch(r"table(\d+)", str(label))
    return int(match.group(1)) if match else 10**9

numeric_cols = [
    "queries",
    "repeats",
    "epsilon",
    "branch_factor",
    "io_size_mean_bytes",
    "io_size_std_bytes",
    "io_size_min_bytes",
    "io_size_p50_bytes",
    "io_size_p75_bytes",
    "io_size_p90_bytes",
    "io_size_p95_bytes",
    "io_size_p99_bytes",
    "io_size_max_bytes",
]
for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

base_cols = [
    "label",
    "index_type",
    "baseline",
    "model",
    "epsilon",
    "branch_factor",
    "policy",
    "cache_bytes",
    "io_mode",
    "strategy",
    "queries",
    "repeats",
]
out = df[[col for col in base_cols if col in df.columns]].copy()
out.insert(1, "workload", df["label"].map(workload_name))
rename_map = {
    "io_size_mean_bytes": "mean_bytes",
    "io_size_std_bytes": "std_bytes",
    "io_size_min_bytes": "min_bytes",
    "io_size_p50_bytes": "p50_bytes",
    "io_size_p75_bytes": "p75_bytes",
    "io_size_p90_bytes": "p90_bytes",
    "io_size_p95_bytes": "p95_bytes",
    "io_size_p99_bytes": "p99_bytes",
    "io_size_max_bytes": "max_bytes",
}
for src, dst in rename_map.items():
    if src in df.columns:
        out[dst] = df[src]

index_rank = {"PGM": 0, "RMI": 1}
out["_label_order"] = out["label"].map(label_order)
out["_index_order"] = out["index_type"].map(index_rank).fillna(99)
out = out.sort_values(["_label_order", "_index_order", "index_type"], kind="stable")
out = out.drop(columns=["_label_order", "_index_order"])
table_csv.parent.mkdir(parents=True, exist_ok=True)
out.to_csv(table_csv, index=False, float_format="%.6f")
PY_IO_TABLE
}

write_rmi_leaf_error_histograms() {
  local rmi_data_dir="$1"
  local bf_list="$2"
  local output_dir="$3"
  local rmi_prefix="$4"
  local rmi_model_tag="$5"
  "$PYTHON_BIN" - "$rmi_data_dir" "$bf_list" "$output_dir" "$rmi_prefix" "$rmi_model_tag" <<'PY_RMI_LEAF_ERRORS'
import csv
import re
import shutil
import struct
import sys
from collections import Counter
from pathlib import Path

rmi_data_dir = Path(sys.argv[1])
bf_spec = sys.argv[2]
output_dir = Path(sys.argv[3])
rmi_prefix = sys.argv[4]
rmi_model_tag = sys.argv[5]
model_base = f"{rmi_prefix}_{rmi_model_tag}"

if not rmi_data_dir.exists():
    raise SystemExit(f"missing RMI data directory: {rmi_data_dir}")

def parse_bf_spec(value):
    tokens = [token for token in re.split(r"[\s,]+", value.strip()) if token]
    if not tokens or any(token.lower() == "all" for token in tokens):
        return None
    out = []
    seen = set()
    for token in tokens:
        bf = int(token)
        if bf not in seen:
            seen.add(bf)
            out.append(bf)
    return out

selected_bfs = parse_bf_spec(bf_spec)
if selected_bfs is None:
    param_files = sorted(rmi_data_dir.glob(f"{model_base}_*_L1_PARAMETERS"))
else:
    param_files = [
        rmi_data_dir / f"{model_base}_{bf}_L1_PARAMETERS"
        for bf in selected_bfs
    ]

if not param_files:
    raise SystemExit(f"no RMI L1 parameter files selected from: {rmi_data_dir}")

output_dir.mkdir(parents=True, exist_ok=True)
manifest_rows = []
record_size = 24

for path in param_files:
    match = re.fullmatch(re.escape(model_base) + r"_(\d+)_L1_PARAMETERS", path.name)
    if not match:
        continue
    branch_factor = int(match.group(1))
    if not path.exists():
        raise SystemExit(f"missing RMI L1 parameter file: {path}")

    data = path.read_bytes()
    if len(data) % record_size != 0:
        raise SystemExit(f"bad RMI L1 parameter size for {path}: {len(data)}")
    leaf_models = len(data) // record_size
    if leaf_models != branch_factor:
        raise SystemExit(
            f"leaf count mismatch for {path}: expected {branch_factor}, got {leaf_models}"
        )

    counts = Counter(
        struct.unpack_from("<Q", data, leaf * record_size + 16)[0]
        for leaf in range(leaf_models)
    )
    model = f"{model_base}_{branch_factor}"
    exported_parameter_file = output_dir / path.name
    if path.resolve() != exported_parameter_file.resolve():
        shutil.copy2(path, exported_parameter_file)

    histogram_csv = output_dir / f"{model}_leaf_error_histogram.csv"
    with histogram_csv.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["model", "branch_factor", "err", "leaf_model_count", "fraction"])
        for err, count in sorted(counts.items()):
            writer.writerow([model, branch_factor, err, count, count / leaf_models])

    manifest_rows.append(
        {
            "model": model,
            "branch_factor": branch_factor,
            "source_parameter_file": str(path),
            "exported_parameter_file": str(exported_parameter_file),
            "histogram_csv": str(histogram_csv),
            "leaf_models": leaf_models,
            "distinct_err_values": len(counts),
            "min_err": min(counts) if counts else 0,
            "max_err": max(counts) if counts else 0,
        }
    )
    print(histogram_csv)

manifest_csv = output_dir / "rmi_leaf_error_histogram_manifest.csv"
with manifest_csv.open("w", newline="") as f:
    fieldnames = [
        "model",
        "branch_factor",
        "source_parameter_file",
        "exported_parameter_file",
        "histogram_csv",
        "leaf_models",
        "distinct_err_values",
        "min_err",
        "max_err",
    ]
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(sorted(manifest_rows, key=lambda row: row["branch_factor"]))
print(manifest_csv)
PY_RMI_LEAF_ERRORS
}
rmi_model_name() {
  printf '%s_%s_%s\n' "$RMI_PREFIX" "$RMI_MODEL_TAG" "$1"
}

prepare_rmi_training_data() {
  if [ ! -f "$RMI_TRAIN_SOURCE_PATH" ]; then
    echo "[error] missing RMI training source: $RMI_TRAIN_SOURCE_PATH" >&2
    exit 1
  fi

  echo "[rmi-train-data] validate $RMI_TRAIN_SOURCE_PATH -> $RMI_TRAIN_DATA_PATH"
  mkdir -p "$(dirname "$RMI_TRAIN_DATA_PATH")"
  "$PYTHON_BIN" - "$RMI_TRAIN_SOURCE_PATH" "$RMI_TRAIN_DATA_PATH" "$NUM_KEYS" <<'PY_RMI_TRAIN_DATA'
import os
import shutil
import struct
import sys
from pathlib import Path

src = Path(sys.argv[1])
dst = Path(sys.argv[2])
explicit_keys = int(sys.argv[3])


def read_u64_at(path, offset):
    with path.open("rb") as f:
        f.seek(offset)
        raw = f.read(8)
    if len(raw) != 8:
        raise SystemExit(f"failed to read uint64 at offset {offset} from {path}")
    return struct.unpack("<Q", raw)[0]


def infer_layout(path, expected_keys=None):
    size = path.stat().st_size
    header_count = read_u64_at(path, 0) if size >= 8 else None

    if expected_keys is not None and expected_keys > 0:
        if header_count == expected_keys and size == 8 + expected_keys * 8:
            return expected_keys, True
        if size == expected_keys * 8:
            return expected_keys, False
        raise SystemExit(
            f"{path} size {size} does not match expected uint64 key count {expected_keys}"
        )

    if header_count is not None and size == 8 + header_count * 8:
        return int(header_count), True
    if size % 8 == 0:
        return size // 8, False
    raise SystemExit(f"cannot infer uint64 key count from {path}")


def key_signature(path, keys, has_header):
    if keys <= 0:
        return ()
    offsets = sorted({0, keys // 2, keys - 1})
    base = 8 if has_header else 0
    return tuple(read_u64_at(path, base + idx * 8) for idx in offsets)


source_keys, source_has_header = infer_layout(src, explicit_keys)
source_sig = key_signature(src, source_keys, source_has_header)

if src.resolve() == dst.resolve():
    if source_has_header:
        print(f"[rmi-train-data] using existing headered data: {dst}")
        raise SystemExit(0)
    raise SystemExit(
        "RMI_TRAIN_DATA_PATH points to the unheadered source file; "
        "choose a different output path so the dataset is not overwritten"
    )

if dst.exists():
    try:
        dst_keys, dst_has_header = infer_layout(dst, source_keys)
        dst_sig = key_signature(dst, dst_keys, dst_has_header)
        if dst_has_header and dst_keys == source_keys and dst_sig == source_sig:
            print(f"[rmi-train-data] reusing validated headered data: {dst}")
            raise SystemExit(0)
        print(
            f"[rmi-train-data] existing target does not match source; rebuilding: {dst}",
            file=sys.stderr,
        )
    except SystemExit as exc:
        if exc.code == 0:
            raise
        print(
            f"[rmi-train-data] existing target failed validation; rebuilding: {dst}: {exc}",
            file=sys.stderr,
        )

dst.parent.mkdir(parents=True, exist_ok=True)
tmp = dst.with_name(dst.name + ".tmp")
try:
    if tmp.exists() or tmp.is_symlink():
        tmp.unlink()
    if source_has_header:
        try:
            os.symlink(os.path.relpath(src, dst.parent), tmp)
            os.replace(tmp, dst)
            print(f"[rmi-train-data] linked existing headered data: {dst}")
            raise SystemExit(0)
        except OSError:
            if tmp.exists() or tmp.is_symlink():
                tmp.unlink()
            shutil.copyfile(src, tmp)
            os.replace(tmp, dst)
            print(f"[rmi-train-data] copied existing headered data: {dst}")
            raise SystemExit(0)

    with src.open("rb") as inp, tmp.open("wb") as out:
        out.write(struct.pack("<Q", source_keys))
        shutil.copyfileobj(inp, out, length=64 * 1024 * 1024)
    os.replace(tmp, dst)
    print(f"[rmi-train-data] wrote headered data: {dst} ({source_keys} keys)")
finally:
    if tmp.exists() or tmp.is_symlink():
        tmp.unlink()
PY_RMI_TRAIN_DATA
}

metadata_value() {
  local path="$1"
  local key="$2"
  sed -n "s/^${key}=//p" "$path" | head -n 1
}

canonical_path() {
  readlink -f "$1" 2>/dev/null || printf '%s\n' "$1"
}

rmi_artifact_is_valid() {
  local model="$1"
  local bf="$2"
  local meta expected_train_real meta_train_real expected_size meta_size expected_mtime meta_mtime

  if [ ! -f "$RMI_DATA_DIR/${model}_L1_PARAMETERS" ] || \
     [ ! -f "$RMI_GENERATED_DIR/${model}.h" ] || \
     [ ! -f "$RMI_GENERATED_DIR/${model}.cpp" ] || \
     [ ! -f "$RMI_GENERATED_DIR/${model}_data.h" ]; then
    return 1
  fi

  meta="$RMI_GENERATED_DIR/${model}.meta"
  if [ ! -f "$meta" ]; then
    meta="$RMI_DATA_DIR/${model}.meta"
  fi
  if [ ! -f "$meta" ]; then
    echo "[rmi-artifact] missing metadata for $model; will regenerate" >&2
    return 1
  fi

  if [ "$(metadata_value "$meta" namespace)" != "$model" ]; then
    echo "[rmi-artifact] metadata namespace mismatch for $model; will regenerate" >&2
    return 1
  fi
  if [ "$(metadata_value "$meta" namespace_prefix)" != "$RMI_PREFIX" ]; then
    echo "[rmi-artifact] metadata prefix mismatch for $model; will regenerate" >&2
    return 1
  fi
  if [ "$(metadata_value "$meta" models)" != "$RMI_MODELS" ]; then
    echo "[rmi-artifact] metadata model-list mismatch for $model; will regenerate" >&2
    return 1
  fi
  if [ "$(metadata_value "$meta" branch_factor)" != "$bf" ]; then
    echo "[rmi-artifact] metadata branch-factor mismatch for $model; will regenerate" >&2
    return 1
  fi

  expected_train_real="$(canonical_path "$RMI_TRAIN_DATA_PATH")"
  meta_train_real="$(metadata_value "$meta" train_data_realpath)"
  if [ -z "$meta_train_real" ] || [ "$meta_train_real" != "$expected_train_real" ]; then
    echo "[rmi-artifact] metadata training data mismatch for $model; will regenerate" >&2
    return 1
  fi

  if [ -f "$RMI_TRAIN_DATA_PATH" ]; then
    expected_size="$(stat -c '%s' "$RMI_TRAIN_DATA_PATH" 2>/dev/null || printf '')"
    meta_size="$(metadata_value "$meta" train_data_size_bytes)"
    if [ -n "$expected_size" ] && [ -n "$meta_size" ] && [ "$meta_size" != "$expected_size" ]; then
      echo "[rmi-artifact] metadata training size mismatch for $model; will regenerate" >&2
      return 1
    fi

    expected_mtime="$(stat -c '%Y' "$RMI_TRAIN_DATA_PATH" 2>/dev/null || printf '')"
    meta_mtime="$(metadata_value "$meta" train_data_mtime_epoch)"
    if [ -n "$expected_mtime" ] && [ -n "$meta_mtime" ] && [ "$meta_mtime" != "$expected_mtime" ]; then
      echo "[rmi-artifact] metadata training mtime mismatch for $model; will regenerate" >&2
      return 1
    fi
  fi

  return 0
}

ensure_rmi_artifacts() {
  local missing_bfs=()
  local bf model
  for bf in $(expand_branch_factor_list "$BF_LIST"); do
    model="$(rmi_model_name "$bf")"
    if ! rmi_artifact_is_valid "$model" "$bf"; then
      missing_bfs+=("$bf")
    fi
  done

  if [ "${#missing_bfs[@]}" -eq 0 ]; then
    return 0
  fi

  echo "[rmi-generate] missing artifacts for ${RMI_PREFIX}_${RMI_MODEL_TAG}: ${missing_bfs[*]}"
  if [ "$RMI_GENERATE" != "1" ]; then
    echo "[error] RMI artifacts are missing and RMI_GENERATE=$RMI_GENERATE" >&2
    echo "        Generate them with $RMI_GENERATOR_SCRIPT or set RMI_GENERATE=1." >&2
    exit 1
  fi
  if [ ! -f "$RMI_GENERATOR_SCRIPT" ]; then
    echo "[error] missing RMI generator script: $RMI_GENERATOR_SCRIPT" >&2
    exit 1
  fi

  prepare_rmi_training_data
  TRAIN_DATA_PATH="$RMI_TRAIN_DATA_PATH" \
  COLLECT_DATA_PATH="$RMI_COLLECT_DATA_PATH" \
  QUERY_PATH="$RMI_COLLECT_QUERY_PATH" \
  COLLECT_DATA_HEADER="$RMI_COLLECT_DATA_HEADER" \
  COLLECT_RECORDS="$RMI_COLLECT_RECORDS" \
  RMI_DATA_DIR="$RMI_DATA_DIR" \
  GENERATED_DIR="$RMI_GENERATED_DIR" \
  MODELS="$RMI_MODELS" \
  NAMESPACE_PREFIX="$RMI_PREFIX" \
  BF_LIST="${missing_bfs[*]}" \
  BUILD_RMI_BENCH=0 \
  BUILD_JOBS="$BUILD_JOBS" \
  bash "$RMI_GENERATOR_SCRIPT"
}


has_rmi_baseline() {
  local baseline
  for baseline in $BASELINES; do
    case "$baseline" in
      RMI|RMI-DIRECT) return 0 ;;
    esac
  done
  return 1
}

baseline_args_for() {
  local baseline="$1"
  case "$baseline" in
    RMI-DIRECT)
      baseline_args=(--algorithms rmi --branch-factors "$BF_CSV" --io-mode direct)
      ;;
    RMI)
      baseline_args=(--algorithms rmi --branch-factors "$BF_CSV" --io-mode buffered)
      ;;
    PGM-DIRECT)
      baseline_args=(--algorithms pgm --epsilons "$EPS_CSV" --io-mode direct)
      ;;
    PGM)
      baseline_args=(--algorithms pgm --epsilons "$EPS_CSV" --io-mode buffered)
      ;;
    *)
      echo "[error] unknown baseline: $baseline" >&2
      echo "        Supported: PGM-DIRECT PGM RMI-DIRECT RMI" >&2
      exit 2
      ;;
  esac
}

: > "$RAW_CSV"

if has_rmi_baseline; then
  ensure_rmi_artifacts
  echo "[rmi-leaf-errors] $RMI_DATA_DIR -> $RMI_LEAF_ERROR_DIR"
  write_rmi_leaf_error_histograms "$RMI_DATA_DIR" "$BF_LIST" "$RMI_LEAF_ERROR_DIR" "$RMI_PREFIX" "$RMI_MODEL_TAG"
fi

for repeat_id in $(seq 1 "$REPEATS"); do
  echo "[repeat] $repeat_id/$REPEATS"
  for table_id in $TABLE_LIST; do
    query_file="$DATASETS_DIRECTORY/$DATASET.${QUERY_TAG}table${table_id}.bin"
    if [ ! -f "$query_file" ]; then
      echo "[error] missing workload: $query_file" >&2
      echo "        Generate it with DATASET=$DATASET bash exp/run_books200m_join_workloads.sh first." >&2
      exit 1
    fi

    for baseline in $BASELINES; do
      baseline_args_for "$baseline"
      run_csv="$TMP_DIR/repeat_${repeat_id}_table${table_id}_${baseline}.csv"
      echo "[*] repeat=${repeat_id} table${table_id} $baseline breakdown -> $run_csv"
      "$BINARY" \
        "${common_args[@]}" \
        "${baseline_args[@]}" \
        --queries "$query_file" \
        --label "table${table_id}" \
        --summary-out "$run_csv"
      append_repeat_csv "$run_csv" "$RAW_CSV" "$repeat_id"
    done
  done
done

echo "[average] $RAW_CSV -> $OUT_CSV"
average_repeat_csv "$RAW_CSV" "$OUT_CSV"

echo "[io-size-table] $OUT_CSV -> $IO_TABLE_CSV"
write_io_size_table "$OUT_CSV" "$IO_TABLE_CSV"

if [ "$PLOT" = "1" ]; then
  echo "[plot] $PLOT_OUTPUT"
  "$PYTHON_BIN" visualize/plot_motivation_query_breakdown.py \
    --summary-csv "$OUT_CSV" \
    --output "$PLOT_OUTPUT" \
    --labels $PLOT_LABELS \
    --formats $PLOT_FORMATS
fi

echo "[+] Done. Averaged results: $OUT_CSV"
echo "[+] IO-size table: $IO_TABLE_CSV"
echo "[+] Raw repeated results: $RAW_CSV"
